In [1]:
# from google.colab import drive
import pandas as pd
import numpy as np

In [2]:
# drive.mount('/content/drive')

In [3]:
data = pd.read_csv('./Dataset/Data.csv')
df = data

In [4]:
independent = df.iloc[:,0:-1].values
dependent = df.iloc[:,-1].values
independent

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [5]:
from sklearn.impute import SimpleImputer

Si = SimpleImputer(missing_values=np.nan,strategy='mean')
independent[:,1:3]  = Si.fit_transform(independent[:,1:3])
independent

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [6]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

Le = LabelEncoder()
test = Le.fit_transform(independent[:,0])
test

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

In [7]:
from sklearn.compose import ColumnTransformer
print(independent)
Ct = ColumnTransformer([("one",OneHotEncoder(),[0])],remainder="passthrough")
independent = Ct.fit_transform(independent)
independent = independent.astype(int)
dependent = Le.fit_transform(dependent).astype(int)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

In [8]:
independent

array([[    1,     0,     0,    44, 72000],
       [    0,     0,     1,    27, 48000],
       [    0,     1,     0,    30, 54000],
       [    0,     0,     1,    38, 61000],
       [    0,     1,     0,    40, 63777],
       [    1,     0,     0,    35, 58000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    48, 79000],
       [    0,     1,     0,    50, 83000],
       [    1,     0,     0,    37, 67000]])

In [9]:
dependent

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

dependent_traing,dependent_testing,independent_traing,independent_testing = train_test_split(dependent,independent,test_size=0.2,random_state=0)

Sc = StandardScaler()
std_independent_trainging  = Sc.fit_transform(independent_traing)
std_independent_testing  = Sc.fit_transform(independent_testing)

filling the missing values with the most repeated

In [11]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/AIML/Dataset/missing country.csv')
df = data
ind = df.iloc[:,0:3].values
ind

Si = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
print(ind[:,0])
ind[:,0] = Si.fit_transform(ind[:,0].reshape(-1,1)).ravel()
print(ind[:,0])

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Colab Notebooks/AIML/Dataset/missing country.csv'

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/AIML/Dataset/bestsellers.csv')
df = data

ind = df.iloc[:,0:6].values
dep = df.iloc[:,-1].values

In [ ]:
from sklearn.impute import SimpleImputer
Si = SimpleImputer(missing_values=np.nan,strategy='mean')
ind[:,2:6] = Si.fit_transform(ind[:,2:6])


from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()
dep = Le.fit_transform(dep)
ind[:,1] = Le.fit_transform(ind[:,1])
ind

array([['10-Day Green Smoothie Cleanse', 114, 4.0, 17350.0, 8.0, 2016.0],
       ['11/22/63: A Novel', 219, 4.0, 2052.0, 22.0, 2011.0],
       ['12 Rules for Life: An Antidote to Chaos', 134, 4.0, 18979.0,
        15.0, 2018.0],
       ...,
       ['Wonder', 188, 4.0, 21625.0, 9.0, 2013.0],
       ['Wrecking Ball (Diary of a Wimpy Kid Book 14)', 120, 4.0, 9413.0,
        8.0, 2019.0],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        121, 4.0, 14331.0, 8.0, 2016.0]], dtype=object)

In [ ]:
from sklearn.preprocessing import StandardScaler

Sc = StandardScaler()
ind[:,1:] = Sc.fit_transform(ind[:,1:])

In [ ]:
from sklearn.model_selection import train_test_split

ind_traing,ind_testing,dep_training,dep_testing = train_test_split(ind,dep,test_size=0.2,random_state=0)

removeing the entrys having the same name

In [ ]:
df = df.drop_duplicates(subset=["Name","Author"], keep="first")
df

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350.0,8.0,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052.0,22.0,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979.0,15.0,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424.0,6.0,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665.0,12.0,2019,Non Fiction
...,...,...,...,...,...,...,...
538,Winter of the World: Book Two of the Century T...,Ken Follett,4.5,10760.0,15.0,2012,Fiction
539,Women Food and God: An Unexpected Path to Almo...,Geneen Roth,4.2,1302.0,11.0,2010,Non Fiction
540,Wonder,R. J. Palacio,4.8,21625.0,9.0,2013,Fiction
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413.0,8.0,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2016,Non Fiction

In [12]:
ind = df.iloc[:,0:6].values
dep = df.iloc[:,-1].values
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
from sklearn.impute import SimpleImputer
Si = SimpleImputer(missing_values=np.nan,strategy='mean')
ind[:,2:6] = Si.fit_transform(ind[:,2:6])
ind

from sklearn.preprocessing import StandardScaler

Sc = StandardScaler()
ind[:,1:] = Sc.fit_transform(ind[:,1:])
ind

from sklearn.model_selection import train_test_split

ind_traing,ind_testing,dep_training,dep_testing = train_test_split(ind,dep,test_size=0.2,random_state=0)

In [ ]:
ind_traing

array([['The Five Dysfunctions of a Team: A Leadership Fable',
        0.6880853726868035, 0.1202117592085863, -0.6074144111694237,
        -0.7051163765766458, -1.377555866359931],
       ['The Tipping Point: How Little Things Can Make a Big Difference',
        0.3061828791610151, 0.1202117592085863, -0.5801479603906956,
        -0.4062083473756765, -1.377555866359931],
       ['Rush Revere and the Brave Pilgrims: Time-Travel Adventures with Exceptional Americans (1)',
        1.0982769398070946, 0.1202117592085863, -0.24419949420819068,
        -0.10730031817470702, -0.15731079609536125],
       ...,
       ['Harry Potter and the Prisoner of Azkaban: The Illustrated Edition (Harry Potter, Book 3)',
        -0.21716498233728748, 0.1202117592085863, -0.6130335108231482,
        1.68614785703111, 1.0629342741692087],
       ['Cutting for Stone', -1.8154976404266983, 0.1202117592085863,
        -0.4545933238656739, -0.2069363279083635, -1.0724945987937886],
       ['National Geographic Kids Why?: Over 1,111 Answers to Everything',
        -1.108270800564127, 0.1202117592085863, -0.4102853413502407,
        0.29124372075991894, 1.6730568093014935]], dtype=object)